- name: Configure webserver
  hosts: webservers
  debugger: on_failed
  gather_facts: True
  tasks:
    - name: install webserver software
      when: ansible_os_family == "Debian"
      become: true
      block:
        - name: install apache2
          ansible.builtin.import_tasks: packages/apache.yml
          tags: [install-apache]
        - name: install php
          ansible.builtin.import_tasks: packages/php.yml
          tags: [install-php]