- name: Configure server
  hosts: webservers
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
    
    - name: Install Mariadb
      apt:
        name: mariadb-server
        state: latest