pipeline {
    agent any
    stages {
        stage('SCM checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/yugarcia/devops-63703.git'
            }
        }

        stage('Execute ansible') {
            steps {
               sh  "ansible-playbook -i  ./DesafioAnsible/inventory.ini ./DesafioAnsible/prueba.yml"
            }
        }
    }
}