- name: Configure webserver
  hosts: wordpress
  gather_facts: True
  vars_files:
    - vars/wordpress.yml
  tasks:
    - name:  install dependencies
      become: yes
      ansible.builtin.import_tasks: packages/dependencies.yml
      tags: [install-dependencies]
    - name: install tools
      become: yes
      ansible.builtin.import_tasks: packages/tools.yml
      tags: [install-tools] 
    - name: install apache
      become: yes
      ansible.builtin.import_tasks: packages/apache.yml
      tags: [install-apache]
    - name: apache security
      become: yes
      ansible.builtin.import_tasks: packages/apache-security.yml
      tags: [apache-security]
    - name: install php-extensions
      become: yes
      ansible.builtin.import_tasks: packages/php-extensions.yml
      tags: [install-php-extensions]
    - name: install mariadb
      become: yes
      ansible.builtin.import_tasks: packages/mariadb.yml
      tags: [install-mariadb]
    - name: app db user
      become: yes
      vars:
        _mysql_admin_user: "{{ mysql_admin_user }}"
        _mysql_admin_password: "{{ mysql_admin_password }}"
        _mysql_wp_db: "{{ mysql_wp_db }}"
        _mysql_wp_user: "{{ mysql_wp_user }}"
        _mysql_wp_password: "{{ mysql_wp_password }}"
      ansible.builtin.import_tasks: packages/app-db-users.yml
      tags: [app-db-user]
    
    - name: configure apache
      become: yes
      vars:
        _apache_server_name: "{{ apache_server_name }}"
        _apache_server_port: "{{ apache_server_port }}"
        _apache_server_admin: "{{ apache_server_admin }}"
      ansible.builtin.import_tasks: packages/apache-config.yml
      tags: [configure-apache]
    - name:  wordpress install
      become: yes
      vars:
        _apache_server_name: "{{ apache_server_name }}"
        _mysql_wp_db: "{{ mysql_wp_db }}"
        _mysql_wp_user: "{{ mysql_wp_user }}"
        _mysql_wp_password: "{{ mysql_wp_password }}"
      ansible.builtin.import_tasks: packages/wordpress-install.yml
      tags: [wordpress-install]
    - name: Intall Grafana
      become: yes
      ansible.builtin.import_tasks: packages/grafana.yml
      tags: [install-grafana]
    - name: Intall Prometheus
      become: yes
      ansible.builtin.import_tasks: packages/prometheus-install.yml
      tags: [install-prometheus]
    - name: Intall Node Exporter
      become: yes
      ansible.builtin.import_tasks: packages/node-exporter.yml
      tags: [install-node-exporter]
    - name: Install Jenkins
      become: yes
      ansible.builtin.import_tasks: packages/install-jenkins.yml
      tags: [install-jenkins]